;
; File generated by cc65 v 2.19 - Git 3d7e3884e
;
	.fopt		compiler,"cc65 v 2.19 - Git 3d7e3884e"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_puts
	.import		_clrscr
	.import		_gotoxy
	.import		_cgetc
	.import		_textcolor
	.import		_bgcolor
	.import		_bordercolor
	.import		_chline
	.export		_main

.segment	"RODATA"

S0104:
	.byte	$C5,$53,$54,$4F,$20,$45,$53,$54,$41,$20,$45,$4E,$20,$41,$4D,$41
	.byte	$52,$49,$4C,$4C,$4F,$0D,$00
S0103:
	.byte	$C8,$4F,$4C,$41,$20,$CD,$55,$4E,$44,$4F,$0D,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _clrscr
	lda     #<(S0103)
	ldx     #>(S0103)
	jsr     _puts
	lda     #$0C
	jsr     _chline
	lda     #$0E
	jsr     _bordercolor
	lda     #$05
	jsr     _bgcolor
	lda     #$0E
	sta     $D020
	lda     #$05
	sta     $D021
	lda     #$07
	jsr     _textcolor
	lda     #$0E
	jsr     pusha
	lda     #$0C
	jsr     _gotoxy
	lda     #<(S0104)
	ldx     #>(S0104)
	jsr     _puts
	jmp     _cgetc

.endproc

